# Generated by Django 5.1.3 on 2024-11-22 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='endpoint',
            field=models.CharField(choices=[('Bishkek', 'Bishkek'), ('Osh', 'Osh'), ('Jalal-Abad', 'Jalal-Abad'), ('Karakol', 'Karakol'), ('Naryn', 'Naryn'), ('Batken', 'Batken'), ('Talas', 'Talas'), ('Tokmok', 'Tokmok')], default='Osh', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='startpoint',
            field=models.CharField(choices=[('Bishkek', 'Bishkek'), ('Osh', 'Osh'), ('Jalal-Abad', 'Jalal-Abad'), ('Karakol', 'Karakol'), ('Naryn', 'Naryn'), ('Batken', 'Batken'), ('Talas', 'Talas'), ('Tokmok', 'Tokmok')], default='Bishkek', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.TextField(default='Default address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
